# Import the theme
theme: jekyll-theme-chirpy

# Language and Timezone
lang: en
timezone: America/Chicago

# Site Metadata
title: Ryan Kerby
tagline: Software Engineer & Aspiring Solutions Architect
description: >-
  Passionate about coding and designing scalable software solutions. Currently honing my skills in software engineering and architecture, eager to bring innovative ideas to life.

# URL Settings
url: "https://ryankerbyIT.github.io"
baseurl: "/blogfolio"

# Social Links and GitHub
github:
  username: ryankerbyIT

social:
  name: Ryan_Kerby
  email: rkerby@memphis.edu
  links:
    - https://github.com/ryankerbyIT

# Site Verification Settings
webmaster_verifications:
  google:
  bing:

# Analytics Settings
analytics:
  google:
    id:
  goatcounter:
    id:

# Site Appearance
theme_mode: # [light | dark]

# Sidebar Avatar
avatar: "./assets/avatar.jpg"

# Post Settings
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/

  - scope:
      path: _drafts
    values:
      comments: false

  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
